# PostgreSQL. Versions 9.3 and up are supported.
#
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'seg_manager_development' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] || 'seg_manager_test' %>

# # # PRODUCTION

production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") %>
    database: <%= ENV.fetch("SEG_MANAGER_DATABASE_NAME") %>
    username: <%= ENV.fetch("SEG_MANAGER_DATABASE_USER") %>
    password: <%= ENV.fetch("SEG_MANAGER_DATABASE_PASSWORD") %>
    host: <%= ENV.fetch("SEG_MANAGER_DATABASE_HOST") %>
    port: <%= ENV.fetch("SEG_MANAGER_DATABASE_PORT") %>

  cache:
    <<: *primary_production
    database: <%= ENV.fetch("SEG_MANAGER_DATABASE_CACHE_NAME") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: <%= ENV.fetch("SEG_MANAGER_DATABASE_QUEUE_NAME") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV.fetch("SEG_MANAGER_DATABASE_CABLE_NAME") %>
    migrations_paths: db/cable_migrate
